"""
visee_optique — Outil A : moteur de géométrie et de réfraction.

Implémente le protocole « Portion visible d'une cible éloignée au-dessus
de la mer » v1.0 (§8 à §11) : géométrie exacte de la portion visible, et
coefficient de réfraction atmosphérique k établi depuis un profil résolu.

Ce paquet ne fait AUCUNE mesure. Il calcule des prédictions et leur
incertitude à partir de faits mesurés, de données externes et
d'hypothèses explicitement déclarées — au sens du Tableau 2 (§6.2) du
protocole — et, avec decision.py, applique au résultat la grille de
lecture du protocole (validité d'image, régimes atmosphériques,
convergence des analystes, recevabilité, verdict à trois valeurs du
§28.3, comparaison de vraisemblance pénalisée du §27.2) sans jamais
mesurer ni décider à la place de l'analyste.
"""

from .geometry import (
    Cible,
    GeometryError,
    arc_to_tangent,
    altitude_from_arc,
    distance_critique,
    distance_limite,
    distance_pour_hauteur_occultee,
    hauteur_occultee,
    fraction_visible,
    fraction_visible_modele_plan,
    arc_approx_petit_angle,
    hauteur_occultee_approx,
    resoudre_altitude_par_dichotomie,
    IUGG_R1,
)

from .refraction import (
    RefractionError,
    RegimeRefraction,
    HypotheseRefraction,
    k_depuis_gradient,
    rayon_effectif,
    classer_regime,
    rapport_conduit_radio_optique,
)

from .geodesy import (
    GeodesyError,
    GRS80_A,
    GRS80_F,
    GRS80_B,
    GRS80_E2,
    rayon_meridien,
    rayon_grande_normale,
    rayon_euler,
    ConversionGeoide,
    altitude_depuis_hauteur_ellipsoidale,
    PosteGeodesique,
    TABLEAU_10,
    incertitude_typique,
    GrandeurGeodesique,
)

from .atmosphere import (
    AtmosphereError,
    ClasseDonnee,
    definition,
    statut_au_rapport,
    DonneeAtmospherique,
    resolution_par_mesure_directe,
    indique_inversion_probable,
    PointProfil,
    ProfilVertical,
    verifier_resolution,
    CoucheK,
    moyenne_ponderee_en_hauteur,
    BORNES_REGIME,
    intervalle_k_faute_de_donnee_resolue,
)

from .models import (
    ModelError,
    Modele,
    ModeleSpherique,
    ModeleSurfacePlane,
    ConditionDiscrimination,
    delta_le_plus_defavorable,
    condition_discrimination,
)

from .uncertainty import (
    UncertaintyError,
    TypeIncertitude,
    Composante,
    Correlation,
    Incertitude,
    composer,
    PlageParametre,
    EnveloppeSensibilite,
    balayer_enveloppe,
    effet_sensibilite,
    modele_refute_par,
)

from .decision import (
    DecisionError,
    Colonne,
    CategorieValiditeImage,
    classer_validite_image,
    majorer_incertitude_si_reserves,
    SignatureRegime,
    RechercheRegime,
    un_regime_est_etabli,
    dispersion_analystes,
    convergence_analystes,
    Z_ALPHA_BILATERAL_0999,
    Z_BETA_PUISSANCE_95,
    taille_echantillon_minimale,
    CriterePenalisation,
    log_vraisemblance_gaussienne,
    critere_penalise,
    ComparaisonModeles,
    comparer_modeles,
    comparer_deux_modeles,
    Recevabilite,
    evaluer_recevabilite,
    ecart_a_enveloppe,
    Verdict,
    ResultatVerdict,
    ElementsVerdict,
    classer_verdict,
    DossierVerdict,
    evaluer_dossier,
)

__all__ = [
    "Cible",
    "GeometryError",
    "arc_to_tangent",
    "altitude_from_arc",
    "distance_critique",
    "distance_limite",
    "distance_pour_hauteur_occultee",
    "hauteur_occultee",
    "fraction_visible",
    "fraction_visible_modele_plan",
    "arc_approx_petit_angle",
    "hauteur_occultee_approx",
    "resoudre_altitude_par_dichotomie",
    "IUGG_R1",
    "RefractionError",
    "RegimeRefraction",
    "HypotheseRefraction",
    "k_depuis_gradient",
    "rayon_effectif",
    "classer_regime",
    "rapport_conduit_radio_optique",
    "UncertaintyError",
    "TypeIncertitude",
    "Composante",
    "Correlation",
    "Incertitude",
    "composer",
    "PlageParametre",
    "EnveloppeSensibilite",
    "balayer_enveloppe",
    "effet_sensibilite",
    "modele_refute_par",
    "ModelError",
    "Modele",
    "ModeleSpherique",
    "ModeleSurfacePlane",
    "ConditionDiscrimination",
    "delta_le_plus_defavorable",
    "condition_discrimination",
    "AtmosphereError",
    "ClasseDonnee",
    "definition",
    "statut_au_rapport",
    "DonneeAtmospherique",
    "resolution_par_mesure_directe",
    "indique_inversion_probable",
    "PointProfil",
    "ProfilVertical",
    "verifier_resolution",
    "CoucheK",
    "moyenne_ponderee_en_hauteur",
    "BORNES_REGIME",
    "intervalle_k_faute_de_donnee_resolue",
    "GeodesyError",
    "GRS80_A",
    "GRS80_F",
    "GRS80_B",
    "GRS80_E2",
    "rayon_meridien",
    "rayon_grande_normale",
    "rayon_euler",
    "ConversionGeoide",
    "altitude_depuis_hauteur_ellipsoidale",
    "PosteGeodesique",
    "TABLEAU_10",
    "incertitude_typique",
    "GrandeurGeodesique",
    "DecisionError",
    "Colonne",
    "CategorieValiditeImage",
    "classer_validite_image",
    "majorer_incertitude_si_reserves",
    "SignatureRegime",
    "RechercheRegime",
    "un_regime_est_etabli",
    "dispersion_analystes",
    "convergence_analystes",
    "Z_ALPHA_BILATERAL_0999",
    "Z_BETA_PUISSANCE_95",
    "taille_echantillon_minimale",
    "CriterePenalisation",
    "log_vraisemblance_gaussienne",
    "critere_penalise",
    "ComparaisonModeles",
    "comparer_modeles",
    "comparer_deux_modeles",
    "Recevabilite",
    "evaluer_recevabilite",
    "ecart_a_enveloppe",
    "Verdict",
    "ResultatVerdict",
    "ElementsVerdict",
    "classer_verdict",
    "DossierVerdict",
    "evaluer_dossier",
]
